#!/bin/bash

# Check if script is run as root
if [[ $EUID -ne 0 ]]; then
  echo "This script must be run with root privileges (sudo)."
  exit 1
fi

duration=$1  # Get the duration argument that was passed to the script

if [[ -z $duration ]]; then
  # Prevent sleep indefinitely for battery and AC power modes when no argument was passed
  pmset -b disablesleep 1
  pmset -c disablesleep 1

  echo "Sleep disabled indefinitely. Press Enter to re-enable sleep."

  # Wait for user to press Enter to reenable sleep
  read -r

  # Revert to the default sleep behavior
  pmset -b disablesleep 0
  pmset -c disablesleep 0
else
  # Separate the time & timescale suffixes
  suffix="${duration: -1}"
  value="${duration%?}"

  # Identify user input's timescale and convert it to seconds
  case "$suffix" in
    s) duration_sec="$value" ;;
    h) duration_sec=$((value * 3600)) ;;
    *) duration_sec="$((duration * 60))" ;;  # Assume minutes suffix other than 'h' & 's' (including no value)
  esac

  # Prevent sleep for the specified duration
  pmset -b disablesleep 1
  pmset -c disablesleep 1

  # Sleep for the specified duration
  sleep "$duration_sec"

  # Revert to the default sleep behavior
  pmset -b disablesleep 0
  pmset -c disablesleep 0
fi
